---
title: "scvi_cluster"
author: "Vanessa Dumeaux"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(reshape2)
library(ggplot2)
library(here)
library(forcats)


iter.files <- list.files("/home/data/release/sc-candida_paper/exp/exp03-scvi", pattern = "_iteration.csv", full.names = TRUE)


labels.files <- c("/home/data/release/sc-candida_paper/data/data03-scvi/csp_2-adjLogcounts_labels.csv",
                  "/home/data/release/sc-candida_paper/data/data03-scvi/fcz_2_3-adjLogcounts_labels.csv",
                  "/home/data/release/sc-candida_paper/data/data03-scvi/fcz_3_6final-adjLogcounts_labels.csv",
                  "/home/data/release/sc-candida_paper/data/data03-scvi/utfczcsprapa-adjLogcounts_labels.csv",
                  "/home/data/release/sc-candida_paper/data/data03-scvi/rapa_2-adjLogcounts_labels.csv",
                  "/home/data/release/sc-candida_paper/data/data03-scvi/ut_0-adjLogcounts_labels.csv")


nms <- c("csp_2", "fcz_2_3", "fcz_3_6final", "utfczcsprapa", "rapa_2", "ut_0")



iter.df <- list()
iter.df <- lapply(1:length(iter.files), function(x){
  orig.labels<- read.csv(labels.files[x])
  colnames(orig.labels)[1] <- "cellid"
  
  scvi <- read.csv(iter.files[x], header = TRUE)
  #rownames(scvi) <- scvi[,1]
  
  scvi.merged <- left_join(scvi, orig.labels[, colnames(orig.labels) %in% c("cellid", "leiden_scVI")])

  
  df <- lapply(dplyr::select(scvi.merged,-c("cellid", "leiden_scVI")), function(clmns){
    dx <- table(clmns, scvi.merged$leiden_scVI)
    max.pred <- apply(dx, 1, which.max)
    col_map <- data.frame(old_names=as.numeric(rownames(dx)),
                          new_names=paste0("cluster", colnames(dx))[max.pred])
  })
  
  scvi.list <- as.list(scvi)[-1]
  renamed_scvi <- t(plyr::ldply(lapply(1:length(scvi.list),function(idx){
    scvi.list[[idx]] <- as.character(scvi.list[[idx]])
    names(scvi.list[[idx]]) <- scvi.list[[idx]]
    
    # rename vector using mapping
    names(scvi.list[[idx]]) <- ifelse(names(scvi.list[[idx]]) %in% df[[idx]]$old_name,
                                      df[[idx]]$new_name[match(scvi.list[[idx]], df[[idx]]$old_name)],
                                      names(scvi.list[[idx]]))
    })))
  
  rownames(renamed_scvi) <- scvi$cellid
  colnames(renamed_scvi) <- colnames(scvi)[-1]
  
  
  scvi.df <- reshape2::melt(renamed_scvi)
  colnames(scvi.df)[1:2] <- c("cellid", "iter")
  
  results <- scvi.df %>% group_by(value) %>% dplyr::count(cellid)
  results.df <- tidyr::spread(results, value, n)
  results.df[is.na(results.df)] <- 0
  
  idx <- apply(results.df[,-1], 1,which.max)+1
  
  iter.cluster <- colnames(results.df)[idx]
  iter.cluster.count <- apply(results.df[,-1], 1, max)
  has_value_gt_50 <- apply(results.df[, -1], 1, function(x) any(x > 50))
  
  results.df$iter.cluster <- iter.cluster
  results.df$has_value_gt_50 <- has_value_gt_50
  results.df$iter.cluster.count <- iter.cluster.count
  results.df$robust.iter.cluster <- paste(iter.cluster, has_value_gt_50, sep = "_")
  
  results.df <- left_join(results.df, orig.labels[, colnames(orig.labels) %in% c("cellid", "leiden_scVI")])
  
  ext.labels <- left_join(orig.labels, results.df[, colnames(results.df) %in% c("cellid", "has_value_gt_50", "iter.cluster", "robust.iter.cluster")])
  
    write.csv(ext.labels, paste0("/home/data/release/sc-candida_paper_revision/data/data03-scvi/", nms[x],"-adjLogcounts_labels_2.csv"), quote = FALSE)
  

  test.df <- results.df %>%
    tidyr::pivot_longer(cols = -c(cellid, has_value_gt_50, leiden_scVI, iter.cluster, robust.iter.cluster, iter.cluster.count), names_to = "cluster", values_to = "count")
  
  test.df <- test.df %>%
    dplyr::arrange(dplyr::desc(count))
  
  return(test.df)
})


names(iter.df) <- nms

# subset(iter.df[[1]],  leiden_scVI %in% c(0, 1, 2, 3) & cluster %in% c("cluster0", "cluster2", "cluster3"))
# factor(cluster, levels = c("cluster0", "cluster2", "cluster3"),labels = c("A","B","C"), ordered = TRUE), fill = count)
# factor(leiden_scVI, levels = c(0,1,2,3), labels = c(1,2,3,4), ordered = TRUE)
p00 <- ggplot(iter.df[[1]], 
             aes(x = fct_reorder(cellid, count),
                 y = factor(cluster, levels = c("cluster0", "cluster2"),
                            labels = c("A", "B"), ordered = TRUE), fill = count)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = 0:2, labels = 0:2, ordered = TRUE), scales = "free", space = "free") +
  labs(title = "Cluster Robustness CSP day 2",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")


p0 <- ggplot(subset(iter.df[[2]], leiden_scVI %in% 0:9 & cluster %in% paste0("cluster", 0:9)), 
             aes(x = fct_reorder(cellid, count),
                 y = factor(cluster, levels = paste0("cluster", 0:9),
                            labels = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"), ordered = TRUE), fill = count)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = 0:9, labels = 0:9, ordered = TRUE), scales = "free", space = "free") +
  labs(title = "Cluster Robustness FCZ day 2 and 3",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")

p1 <- ggplot(subset(iter.df[[3]],  leiden_scVI %in% c(0, 1, 2, 3) & cluster %in% c("cluster0", "cluster2", "cluster3")), 
             aes(x = fct_reorder(cellid, count), 
                 y =  factor(cluster, levels = c("cluster0", "cluster2", "cluster3"),labels = c("A","B","C"), ordered = TRUE), fill = count)) +
geom_tile() +
   scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = c(0,1,2,3), labels = c(1,2,3,4), ordered = TRUE), scales = "free", space = "free") +
  labs(title = "Cluster Robustness FCZ day3 & day6",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")

    
p2 <- ggplot(subset(iter.df[[4]], leiden_scVI %in% c(0, 1, 2, 3, 4) 
                    & cluster %in% c("cluster0", "cluster1", "cluster2", "cluster3")), 
             aes(x = fct_reorder(cellid, count),
                 y = factor(cluster, levels = c("cluster0", "cluster2", "cluster1", "cluster3"),
                            labels = c("A", "B", "C", "D"), ordered = TRUE), fill = count)) +
  geom_tile() +
  scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = c(0,1,2,3,4), labels = c(1, 2,3, 4,5), ordered = TRUE), scales = "free", space = "free") +
  labs(title = "Cluster Robustness UT FCZ CSP RAPA",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")


p31 <- ggplot(subset(iter.df[[5]], leiden_scVI %in% c(0, 1, 2) 
                    & cluster %in% c("cluster0", "cluster1", "cluster2")),
             aes(x = fct_reorder(cellid, count), y = factor(cluster, levels = c("cluster0", "cluster1", "cluster2"),labels = c("A","B","C"), ordered = TRUE), fill = count)) +
geom_tile() +
   scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = c(2,0,1), labels = c(1,2,3), ordered = TRUE), 
             scales = "free", space = "free") +

  labs(title = "Cluster Robustness RAPA",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")

p32 <- ggplot(subset(iter.df[[6]], leiden_scVI %in% c(0, 1, 2) 
                    & cluster %in% c("cluster0", "cluster1", "cluster2")),
             aes(x = fct_reorder(cellid, count), y = factor(cluster, levels = c("cluster0", "cluster1", "cluster2"),labels = c("A","B","C"), ordered = TRUE), fill = count)) +
geom_tile() +
   scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = c(2,0,1), labels = c(1,2,3), ordered = TRUE), 
             scales = "free", space = "free") +

  labs(title = "Cluster Robustness UT",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")

p33 <- ggplot(subset(iter.df[[6]], leiden_scVI %in% c(0, 1, 2)),
             aes(x = fct_reorder(cellid, count), y = cluster, fill = count)) +
geom_tile() +
   scale_fill_gradient2(low = "white", mid = "white", high = "blue", midpoint = 30) +
  facet_grid(~ factor(leiden_scVI, levels = c(2,0,1), labels = c(1,2,3), ordered = TRUE), 
             scales = "free", space = "free") +

  labs(title = "Cluster Robustness UT",
       x = "Cell ID",
       y = "Cluster",
       fill = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(strip.background = element_blank(),
        panel.border = element_rect(colour = "lightgrey", fill = NA),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom",
        legend.direction = "horizontal")


pdf("output/cluster_robustness.pdf")
print(p00)
print(p0)
print(p31)
print(p32)
print(p2)
print(p1)
dev.off()


```
```{r}
iter.df[[6]] %>%                               # Summary by group using dplyr
  group_by(leiden_scVI) %>% 
  summarize(gt_50 = sum(has_value_gt_50),
            mean_iter = mean(iter.cluster.count),
            median_iter = median(iter.cluster.count),
            max_iter = max(iter.cluster.count))
```

