---
title: "hsf1-rastr exploration"
author: "Vanessa Dumeaux"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(VISION)
library(here)
library(ggplot2)
library("LaCroixColoR")
library(reshape2)
library(viridis)
library(viridisLite)
library(RColorBrewer)
library(here)
library(pheatmap)
library(dplyr)
library(readxl)
library(reshape2)


source(here("src", "bresat.R"))
```

# Single-cell data analyses ------------

## Import scvi, magic counts and VISION results

```{r}
vis.pth <- here("data", "data04-VISION")
scvi.pth <- here("data", "data03-scvi")
    
finalall <- readRDS(file.path(vis.pth, "utfczcsprapa-adjLogcounts_vis_hsf1-rastr.rds"))

counts <- read.csv(file.path(scvi.pth, "utfczcsprapa-adjLogcounts_magic.csv"))
counts <- subset(counts, select = -c(X))
dim(counts)

all.latent <- finalall@LatentSpace
all.metadata <- finalall@metaData
sig.scores <- finalall@SigScores

```


```{r}

cl.tb <- table(all.metadata$leiden_scVI)
cl.tb


cl.sel <- names(cl.tb)[cl.tb < 200]

all.metadata$leiden_scVI_2 <- as.character(all.metadata$leiden_scVI)
all.metadata$leiden_scVI_2[all.metadata$leiden_scVI %in% cl.sel] <- "others"
all.metadata$leiden_scVI_2 <- dplyr::recode_factor(all.metadata$leiden_scVI_2, "0" = "cluster1", "1" = "cluster2", "2" = "cluster3",
                                         "3" = "cluster4", "4" = "cluster5", "others" = "others")


table(all.metadata$leiden_scVI_2, all.metadata$drug_day)


table(all.metadata$leiden_scVI_2)
table(all.metadata$drug_day)

colnames(all.latent) <- c("UMAP1", "UMAP2")

full.df <- cbind(all.latent, all.metadata, sig.scores)

full.df <- full.df[, !duplicated(colnames(full.df))]

```



## Figure 4
```{r}
library(ggplot2)

p2 <- ggplot(subset(full.df, !leiden_scVI_2 %in% c("others")), 
             aes(x=UMAP1, y=UMAP2)) +
  geom_point(size = 0.4, col = "gray80") +
      theme_void()



p.hsf1 <- p2 + 
  geom_point(data = subset(full.df, leiden_scVI_2 %in% c("cluster1", "cluster4")), 
             mapping = aes(x=UMAP1, y=UMAP2, col = hsf1_constitutive), size = 0.4)+ 
    scale_color_viridis_c()



p.hsf1


ggsave("output/figure4b-revision-umap_hsf1.pdf", p.hsf1, width = 4, height = 3)

```
```{r}
p.rastr.up <-  p2 + 
  geom_point(data = subset(full.df, leiden_scVI_2 %in% c("cluster1", "cluster4")), 
             mapping = aes(x=UMAP1, y=UMAP2, col = rastr_UP), size = 0.4) +
  scale_color_viridis_c()

p.rastr.up

ggsave("output/figure4a-revision-umap_rastr_up.pdf", p.rastr.up, width = 4, height = 3)


```

