---
title: "Compare day3 and day6 Go terms for alpha & beta cells"
author: "Vanessa Dumeaux"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
set.seed(321)
library(ViSEAGO)
library(ggplot2)

library(LaCroixColoR)

scvi.pth <- here("data", "data03-scvi")
source(here("src", "utils.R"))


```



# compare with day 3and day 6 fcz alpha cells
```{r}
day3 <- read.table("../exp07-figure3/output/figure3suppTable2a-siggenes_fcz_alphaXbeta_fdr0.1.txt", 
            sep="\t", header = TRUE)


day3.genes <- day3$gene
day3.genes.up <- day3$gene[day3$log2FoldChange > 0]
day3.genes.dn <- day3$gene[day3$log2FoldChange < 0]

```

```{r}
day6 <- read.table("../exp08-figure4/output/figure4suppTable1a-siggenes_fczday6_alphaXbeta_fdr0.1.txt", 
            sep="\t", header = TRUE)


day6.genes <- day6$gene
day6.genes.up <- day6$gene[day6$log2FoldChange > 0]
day6.genes.dn <- day6$gene[day6$log2FoldChange < 0]

```


```{r}
genesl <- list()
genesl$all.day6 <- day6.genes
genesl$up.day6 <- day6.genes.up # up in alpha at day 6
genesl$dn.day6 <- day6.genes.dn # up in beta at day 6
genesl$all.day3 <- day3.genes 
genesl$up.day3 <- day3.genes.up # up in alpha at day 3
genesl$dn.day3 <- day3.genes.dn # up in beta at day 3

str(genesl)
```

```{r}
table(genesl$all.day6 %in% genesl$all.day3)
df <- cbind(c(315, 553), c(482,3927))
df
fisher.test(df)

```



```{r}
raw.counts <- read.csv(file.path(scvi.pth, "fcz_3_6final_raw.csv"), row.names = 1)

bckg <- colnames(raw.counts)
```

```{r}

library(ViSEAGO)
library("LaCroixColoR")
Custom<-ViSEAGO::Custom2GO(here("data","ca.goa.txt"))

myGENE2GO<-ViSEAGO::annotate(
    "237561",
    Custom
)
```

```{r}
goterms <- lapply(genesl, function(x){
  BP.markers<-ViSEAGO::create_topGOdata(
    geneSel = x, 
    allGenes = bckg,
    gene2GO=myGENE2GO, 
    ont="BP",
    nodeSize=5
  )
  
  weight01.BP.markers<-topGO::runTest(
      BP.markers,
      statistic = "fisher"
  )
  return(list(bp=BP.markers, weight01.bp = weight01.BP.markers))
})

saveRDS(goterms, "output/goterms_day3day6_alphabeta.rds")
```
